name: 01 - Hello CI/CD

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Afficher un message de bienvenue
        run: echo "Bienvenue dans la CI/CD pour l'API de satisfaction !"

      - name: Afficher la date et l'heure
        run: date