name : Premier workflow
on: workflow_dispatch
jobs:
  premier-job:
    name: premier job
    runs-on: ubuntu-latest
    steps:
      - name: Dit bonjour
        run: echo 'hello world'
      - name: Dit au revoir
        run: echo 'Goodbye'